### PR TITLE
Add database snapshot with test data

### PR DESCRIPTION
**Pull request by korDen**
This is a database snapshot from a test server with all sensitive information removed. It can be used for local development as a decent representation of a production database.

### CODE REVIEW

**Comment by mrhappyasthma** [comment]
Do we want this to be checked in? Would it be easier to just store it on google drive or somewhere external?

(I guess the file isn't that big. so perhaps checking it into the repo is fine?)

**Comment by korDen** [comment]
Either way is fine but this may be more accessible/easier to find. I don't have a strong preference either way.

**Comment by mrhappyasthma** [comment]
I guess the downside here is that updating it will require a PR every time. (Although the history will be easier to track since it's publicly version controlled).

I was thinking cloud file share is nice because you can always just drag-and-drop the latest version to update it without needing a formal process.

I'm fine either way.

(Also, regardless, we should add a wiki entry about how to create a new version of this as the DB schema changes)

**Comment by mrhappyasthma** [comment]
Approving in case we decide to merge this:

**Review by mrhappyasthma — APPROVED** [review]

**Review by cptwonton — APPROVED** [review]

**Pull request merged**
