### PR TITLE
Add initial ChatServer setup

### PR DESCRIPTION
**Pull request by korDen**
Fairly big commit containing majority of the ChatServer infrastructure code.

### CODE REVIEW

**Comment by cptwonton** [comment]
this is a large commit so i could only keep so much context in mind while reviewing.

taking a step back, I'm wondering if it makes sense at all to split the open source skeleton king (master server?) into multiple baby microservices. since we're taking a modular approach, to me it makes sense to hold, say, the chat server in it's own container? did you consider the pro/con of splitting this across several hosts?

**Comment by korDen** [comment]
Unfortunately, it kind of has to be a big commit becuase it even to process a basic message you need a lot of abstractions and functionality:
- listen to the port and accept new connections
- read incoming data into a dynamic buffer
- decode data from the incoming data buffer using an extensible message factory
- have a per-client connection object with the state
etc

I can move the ConnectRequest into its own PR but I was worried that it would be hard to understand how it all works together without a sample Request/Response.
Hopefully, follow up PRs will be easier to understand.

**Comment by korDen** [comment]
There is also a fair amount of dependant changes which make it look like a bigger change than it actually is. Hopefully we can check them in soon.

**Comment by korDen** [comment]
Removed ConnectRequest and all classes/methods not used by it.

**Comment by korDen** [comment]
Moved into a separate project and added some basic tests.

**Review by Loop1sh — APPROVED** [review]
Looks good to merge

**Review by Loop1sh — APPROVED** [review]
Re-approving with updated access.

**Comment by mrhappyasthma** [comment]
I haven't had a chance to go through this yet. It's quite large.

If possible, can we add a wiki entry outlining the basic infra of the chat server and how to add a new message (I'm imaging something akin to a one-pager + a codelab)

**Comment by korDen** [comment]
> I haven't had a chance to go through this yet. It's quite large.
> 
> If possible, can we add a wiki entry outlining the basic infra of the chat server and how to add a new message (I'm imaging something akin to a one-pager + a codelab)

Will do but that separate if that's ok.

**Pull request merged**
